name: Expo Publish on Push to Development
on:
  push:
    branches:
      - development
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - uses: expo/expo-github-action@v7
        with:
          expo-version: 4.x
          eas-version: latest
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: eas build --platform android --non-interactive
